
POST http://localhost:3003/createTeam
Content-Type: application/json

{
   "name": "Alves"
}

###

GET http://localhost:3003/getTeamsActive

###

PUT http://localhost:3003/changeModule/33bc0b0c-8b78-4bbf-b30f-fd0eadb726b2
Content-Type: application/json

{
    "module": "Module01"
}

###
POST http://localhost:3003/createStudent
Content-Type: application/json

{
    "name": "Saullp",
    "email": "saullo@email.com",
    "birth_date": "1992/01/01",
    "teamId": "e372416e-ff73-40f6-8f76-3945717f184a"
}

###
GET http://localhost:3003/student/Rommel

###
PUT http://localhost:3003/changeStudentTeam/3a9d6438-7468-46ad-80d3-f4022c985971
Content-Type: application/json

{
    "name": "Aragon"
}

###
POST http://localhost:3003/createTeacher
Content-Type: application/json

{
    "name": "Michelan",
    "email": "michelan@email.com",
    "birth_date": "1980/01/01",
    "teamId": "33bc0b0c-8b78-4bbf-b30f-fd0eadb726b2"
}

###
GET http://localhost:3003/getTeachers